/**
 * Filesystem locations, resolved from this module rather than from
 * `process.cwd()`.
 *
 * cwd is not stable here: `pnpm dev` runs from `server/`, `pnpm test` from the
 * workspace root, and the container from `/app`. Anything anchored to cwd works
 * in exactly one of those.
 *
 * There are two different anchors below, and the difference matters:
 *
 *  - **Assets that ship with the code** resolve relative to *this module*, so
 *    they follow the build. Under `tsx` that is `src/`; after `pnpm build` it is
 *    `dist/`, where the build step has copied them. `tsc` emits no
 *    non-TypeScript files, so anything here must be copied by the build script —
 *    see `package.json`.
 *  - **The SPA build output** resolves from the `server` package root, because
 *    `public/` sits beside `src/` and `dist/` rather than inside either.
 */

import { existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/** The directory this module was loaded from: `src/` in dev, `dist/` when built. */
export const CODE_ROOT = dirname(fileURLToPath(import.meta.url));

/**
 * Walk up from the code root until a `package.json` appears — that directory is
 * the `server` package root, whether we are running from `src/` or `dist/`.
 */
function findServerRoot(startDir: string): string {
  let dir = startDir;

  for (;;) {
    if (existsSync(join(dir, 'package.json'))) return dir;

    const parent = dirname(dir);
    if (parent === dir) {
      throw new Error(`Could not locate the server package root above ${startDir}`);
    }
    dir = parent;
  }
}

export const SERVER_ROOT = findServerRoot(CODE_ROOT);

/** Built SPA assets. Generated by LAI-007, gitignored, absent in a clean clone. */
export const PUBLIC_DIR = resolve(SERVER_ROOT, 'public');

/**
 * The committed document served when no SPA build is present (CHIEF decision on
 * LAI-016).
 *
 * Anchored to `CODE_ROOT`, not to `src/`: a container ships `dist/` alone, so a
 * path pointing into `src/` would resolve to a file that is not in the image and
 * the SPA fallback would 500 in production while passing every test locally.
 */
export const FALLBACK_DOCUMENT = resolve(CODE_ROOT, 'static/fallback.html');
