/**
 * Filesystem locations, resolved from this module rather than from
 * `process.cwd()`.
 *
 * cwd is not stable here: `pnpm dev` runs from `server/`, `pnpm test` from the
 * workspace root, and the container runs from `/app`. Anything anchored to cwd
 * works on exactly one of those.
 */

import { existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Walk up from this file until a `package.json` appears — that directory is the
 * `server` package root. This survives both `src/` under tsx and a future
 * `dist/` build, which sit at different depths.
 */
function findServerRoot(startDir: string): string {
  let dir = startDir;

  for (;;) {
    if (existsSync(join(dir, 'package.json'))) return dir;

    const parent = dirname(dir);
    if (parent === dir) {
      throw new Error(`Could not locate the server package root above ${startDir}`);
    }
    dir = parent;
  }
}

export const SERVER_ROOT = findServerRoot(dirname(fileURLToPath(import.meta.url)));

/** Built SPA assets. Generated by LAI-007, gitignored, absent in a clean clone. */
export const PUBLIC_DIR = resolve(SERVER_ROOT, 'public');

/**
 * The committed document served when no SPA build is present (PM decision on
 * LAI-016). It lives in `src/`, never in `public/` — nothing is ever committed
 * into the build output directory.
 */
export const FALLBACK_DOCUMENT = resolve(SERVER_ROOT, 'src/static/fallback.html');
